# Generated by Django 3.0.3 on 2021-01-15 06:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardCalculator', '0002_auto_20210115_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airtelprovider',
            options={'verbose_name': 'AIRTEL Card', 'verbose_name_plural': 'AIRTEL Cards'},
        ),
        migrations.AlterModelOptions(
            name='gloprovider',
            options={'verbose_name': 'GLO Card', 'verbose_name_plural': 'GLO Cards'},
        ),
        migrations.RemoveField(
            model_name='airtelprovider',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='gloprovider',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='mtnprovider',
            name='total_balance',
        ),
        migrations.AlterField(
            model_name='mtnprovider',
            name='price_per_pack',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The price for every pack of airtime cards, eg ->  550 cards price * number of cards per pack ', max_digits=9),
        ),
    ]
