# Generated by Django 3.0.3 on 2021-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardCalculator', '0003_auto_20210115_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimeprovider',
            name='card_pack',
            field=models.CharField(choices=[('10', '_10_Pack'), ('20', '_20_Pack')], default=None, help_text='The type of pack these cards come in, either 10 or 20 cards in each pack', max_length=254, verbose_name='Card Pack'),
        ),
        migrations.AlterField(
            model_name='airtimeprovider',
            name='card_type',
            field=models.CharField(choices=[('500', '_500_CARD'), ('200', '_200_CARD'), ('100', '_100_CARD')], default=None, help_text='The type of card -> 500, 200, or 100', max_length=254, verbose_name='Card_Type'),
        ),
    ]
